### PR TITLE
Add support for select boxes.

### PR DESCRIPTION
**Pull request by EdAyers**
Allows 'onChange' to be called on `<select>` html elements. Which means that we can support dropdown boxes (helper function in lean tbc).

Eg:

image

### CODE REVIEW

**Comment by bryangingechen** [comment]
Older versions of Lean still won't get a tactic state filter, right?

**Comment by EdAyers** [comment]
Yep see https://github.com/leanprover-community/lean/pull/346 for the filtering

**Comment by EdAyers** [comment]
It should be not too hard to re-add the filtering menu for the non-widget tactic state, I think that all of the filtering code is still there its just the dropdown is gone.

**Comment by EdAyers** [comment]
Could you post some examples of `infoViewTacticStateFilters` config entry so I can test it?

**Comment by bryangingechen** [comment]
Hmm, I think I've only used the two filters in `package.json`. Maybe we could ask in Zulip?

**Pull request merged**
