### PR TITLE
exclude angle brackets in wordPattern

### PR DESCRIPTION
**Pull request by kckennylau**
per https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/VScode.20extension/near/184537385

### CODE REVIEW

**Comment by gebner** [comment]
Did you test this?

**Comment by kckennylau** [comment]
I haven't.

**Comment by bryangingechen** [comment]
I just did a little testing and it seemed to work for me. Only suggestion I'd make is to add the following characters as well: `⦃⦄⟦⟧⟮⟯‹›`.

**Comment by kckennylau** [comment]
done

**Pull request merged**
