### PR TITLE
Shortcuts for `⋖` and `⋗`

### PR DESCRIPTION
**Pull request by YaelDillies**
This adds `covers` and `<:` as shortcuts for `⋖`, as well as `:>` for `⋗`.

This corresponds to the covering relation in order theory.

### CODE REVIEW

**Comment by gebner** [comment]
Is there a related mathlib PR?

**Comment by YaelDillies** [comment]
It corresponds to https://leanprover-community.github.io/mathlib_docs/order/cover.html#covers

**Comment by gebner** [comment]
Relevant mathlib PR: https://github.com/leanprover-community/mathlib/pull/10676

**Comment by gebner** [comment]
Copied to vscode-lean4 and lean.nvim.  Could you please create PRs for https://github.com/leanprover/lean-mode/ and https://github.com/leanprover/lean4-mode/?

**Pull request merged**
