### PR TITLE
 Add `\specializes` → ⤳ abbreviation

### PR DESCRIPTION
**Pull request by erdOne**
For mathlib#10914

### CODE REVIEW

**Comment by gebner** [comment]
Please also add it under the `\∼>` abbreviation.

**Comment by jcommelin** [comment]
@gebner what's the status here?

**Comment by gebner** [comment]
Completely forgot about this.  Relevant zulip discussion: https://leanprover.zulipchat.com/#narrow/stream/144837-PR-reviews/topic/https.3A.2F.2Fgithub.2Ecom.2Fleanprover.2Fvscode-lean.2Fpull.2F285

**Comment by gebner** [comment]
The emacs extension also has the abbreviation now, so let's merge this.

**Pull request merged**
