### PR TITLE
Revert infoview:getMediaPath

### PR DESCRIPTION
**Pull request by sjkillen**
Revert getMediaPath method to the one used in v0.15.5
This allows the info view to work in vscode remote fixing #208

### CODE REVIEW

**Comment by bryangingechen** [comment]
Rather than just revert this one instance, I would look at all the changes in https://github.com/leanprover/vscode-lean/commit/3b60fae4d95079beae2701a1f9a12995367dcece#diff-26aa7a3396b0249064623d10481785a2 (except for the change to `package_lock.json`) and revert those as well.

**Comment by sjkillen** [comment]
Are there tests to be run in the launch tests task? When I launch the task it complains about `/out/test` being missing but the extension seems to work when I use it

**Comment by bryangingechen** [comment]
I've never actually tried running the tests myself, so I'm fairly certain the answer is no. There do seem to be some tests in the `test/` directory but they don't look particularly useful. 

Regarding the complaint from the task, from what I can tell, `out/test/` is where any output files should end up, not where the tests are / would be located, so probably https://github.com/leanprover/vscode-lean/blob/2fd4cab7ed3ff0dffaeb21e9d5cd6eff9530e0fe/.vscode/launch.json#L21 should be changed so that `extensionTestsPath` points to `${workspaceRoot}/test` instead.

**Comment by gebner** [comment]
I'd feel infinitely more comfortable with this change if we only use `asWebviewUri` for vscode versions where it has been fixed.

There are indeed no tests for the extension.  Even worse, the `asWebviewUri` bug is non-deterministic.  I could never reproduce it using `F5`, only when installing the extension regularly.

**Comment by sjkillen** [comment]
I've added a switch to resort back to staticserver if the vscode version is less than 1.46.0 (https://github.com/leanprover/vscode-lean/issues/162#issuecomment-630549016)

I've only been testing outside the extension development host as I'm not sure it works for VScode remote

**Comment by gebner** [comment]
I've bumped the required vscode version to 1.47 because I still got the unknown url scheme error on 1.46.1.  I think they delayed the fix by one version.

**Comment by gebner** [comment]
Reference for delay: https://github.com/microsoft/vscode/issues/89038#issuecomment-637161257

**Pull request merged**
